/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConnecting: typeof import('./src/components/AppConnecting.vue')['default']
    ComponentTreeNode: typeof import('./src/components/components/ComponentTreeNode.vue')['default']
    DevToolsLogo: typeof import('./src/components/common/DevToolsLogo.vue')['default']
    IconTitle: typeof import('./src/components/common/IconTitle.vue')['default']
    PanelGrids: typeof import('./src/components/common/PanelGrids.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RoutesTable: typeof import('./src/components/pages/RoutesTable.vue')['default']
    SectionBlock: typeof import('./src/components/common/SectionBlock.vue')['default']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    SideNavItem: typeof import('./src/components/SideNavItem.vue')['default']
    TabIcon: typeof import('./src/components/TabIcon.vue')['default']
  }
}
