/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConnecting: typeof import('./src/components/AppConnecting.vue')['default']
    AssetDetails: typeof import('./src/components/assets/AssetDetails.vue')['default']
    AssetFontPreview: typeof import('./src/components/assets/AssetFontPreview.vue')['default']
    AssetGridItem: typeof import('./src/components/assets/AssetGridItem.vue')['default']
    AssetListItem: typeof import('./src/components/assets/AssetListItem.vue')['default']
    AssetPreview: typeof import('./src/components/assets/AssetPreview.vue')['default']
    ChildStateViewer: typeof import('./src/components/state/ChildStateViewer.vue')['default']
    CodeBlock: typeof import('./src/components/code/CodeBlock.vue')['default']
    CodeSnippets: typeof import('./src/components/code/CodeSnippets.vue')['default']
    ComponentTreeNode: typeof import('./src/components/components/ComponentTreeNode.vue')['default']
    CustomTabComponent: typeof import('./src/components/CustomTabComponent.vue')['default']
    DevToolsHeader: typeof import('./src/components/basic/DevToolsHeader.vue')['default']
    DevToolsLogo: typeof import('./src/components/common/DevToolsLogo.vue')['default']
    DockingPanel: typeof import('./src/components/common/DockingPanel.vue')['default']
    Empty: typeof import('./src/components/basic/Empty.vue')['default']
    FilepathItem: typeof import('./src/components/assets/FilepathItem.vue')['default']
    GraphDrawer: typeof import('./src/components/graph/GraphDrawer.vue')['default']
    GraphFileType: typeof import('./src/components/graph/GraphFileType.vue')['default']
    GraphNavbar: typeof import('./src/components/graph/GraphNavbar.vue')['default']
    IconTitle: typeof import('./src/components/common/IconTitle.vue')['default']
    IframeView: typeof import('./src/components/common/IframeView.vue')['default']
    Navbar: typeof import('./src/components/common/Navbar.vue')['default']
    NodeTag: typeof import('./src/components/basic/NodeTag.vue')['default']
    PagePathItem: typeof import('./src/components/pages/PagePathItem.vue')['default']
    PageTable: typeof import('./src/components/pages/PageTable.vue')['default']
    PanelGrids: typeof import('./src/components/common/PanelGrids.vue')['default']
    RootStateViewer: typeof import('./src/components/state/RootStateViewer.vue')['default']
    RouteMetaDetail: typeof import('./src/components/pages/RouteMetaDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionBlock: typeof import('./src/components/common/SectionBlock.vue')['default']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    SideNavItem: typeof import('./src/components/SideNavItem.vue')['default']
    StateFieldEditor: typeof import('./src/components/state/StateFieldEditor.vue')['default']
    StateFieldInputEditor: typeof import('./src/components/state/StateFieldInputEditor.vue')['default']
    StateFieldViewer: typeof import('./src/components/state/StateFieldViewer.vue')['default']
    TabIcon: typeof import('./src/components/TabIcon.vue')['default']
    ToggleExpanded: typeof import('./src/components/basic/ToggleExpanded.vue')['default']
    TopNav: typeof import('./src/components/basic/TopNav.vue')['default']
    TreeViewer: typeof import('./src/components/tree/TreeViewer.vue')['default']
  }
}
