/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConnecting: typeof import('./src/components/AppConnecting.vue')['default']
    AssetDetails: typeof import('./src/components/assets/AssetDetails.vue')['default']
    AssetFontPreview: typeof import('./src/components/assets/AssetFontPreview.vue')['default']
    AssetGridItem: typeof import('./src/components/assets/AssetGridItem.vue')['default']
    AssetListItem: typeof import('./src/components/assets/AssetListItem.vue')['default']
    AssetPreview: typeof import('./src/components/assets/AssetPreview.vue')['default']
    CodeBlock: typeof import('./src/components/code/CodeBlock.vue')['default']
    CodeSnippets: typeof import('./src/components/code/CodeSnippets.vue')['default']
    ComponentTreeNode: typeof import('./src/components/components/ComponentTreeNode.vue')['default']
    DevToolsLogo: typeof import('./src/components/common/DevToolsLogo.vue')['default']
    FilepathItem: typeof import('./src/components/assets/FilepathItem.vue')['default']
    IconTitle: typeof import('./src/components/common/IconTitle.vue')['default']
    IframeView: typeof import('./src/components/common/IframeView.vue')['default']
    Navbar: typeof import('./src/components/common/Navbar.vue')['default']
    PanelGrids: typeof import('./src/components/common/PanelGrids.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RoutesTable: typeof import('./src/components/pages/RoutesTable.vue')['default']
    SectionBlock: typeof import('./src/components/common/SectionBlock.vue')['default']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    SideNavItem: typeof import('./src/components/SideNavItem.vue')['default']
    StateFields: typeof import('./src/components/state/StateFields.vue')['default']
    StateFieldsTree: typeof import('./src/components/state/StateFieldsTree.vue')['default']
    TabIcon: typeof import('./src/components/TabIcon.vue')['default']
    ToggleExpanded: typeof import('./src/components/common/ToggleExpanded.vue')['default']
  }
}
