/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/assets': RouteRecordInfo<'/assets', '/assets', Record<never, never>, Record<never, never>>,
    '/components': RouteRecordInfo<'/components', '/components', Record<never, never>, Record<never, never>>,
    '/console': RouteRecordInfo<'/console', '/console', Record<never, never>, Record<never, never>>,
    '/custom-tab-view/[name]': RouteRecordInfo<'/custom-tab-view/[name]', '/custom-tab-view/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/documents': RouteRecordInfo<'/documents', '/documents', Record<never, never>, Record<never, never>>,
    '/graph': RouteRecordInfo<'/graph', '/graph', Record<never, never>, Record<never, never>>,
    '/inspect': RouteRecordInfo<'/inspect', '/inspect', Record<never, never>, Record<never, never>>,
    '/overview': RouteRecordInfo<'/overview', '/overview', Record<never, never>, Record<never, never>>,
    '/pages': RouteRecordInfo<'/pages', '/pages', Record<never, never>, Record<never, never>>,
    '/pinia': RouteRecordInfo<'/pinia', '/pinia', Record<never, never>, Record<never, never>>,
    '/visualizer': RouteRecordInfo<'/visualizer', '/visualizer', Record<never, never>, Record<never, never>>,
  }
}
