import process from 'node:process'

// 插件启动日志（面板 URL / 探针地址）是 CLI 场景的核心输出，属合理 console 使用
/* eslint-disable no-console */
import os from 'node:os'
import type { Plugin, ResolvedConfig } from 'vite'
import Inspect from 'vite-plugin-inspect'
import { createDevServer } from 'devframe/adapters/dev'
import { createInteractiveAuth } from 'devframe/recipes/interactive-auth'
import { randomToken } from 'devframe/utils/crypto-token'
import { AGENT_CLIENT_MARKER, AgentRegistry } from './relay.ts'
import { createUniDevtoolsDevframe, resolveClientAssets } from './devframe.ts'
import { INSPECT_OUTPUT_DIR, createInspectApp } from './inspect-serve.ts'
import { injectEntryFileGuard, injectPlainRenderHook, injectSetupBindings, resolveVirtualEntryFile } from './instrument.ts'

const BASE = '/__uni-devtools/'
const VIRTUAL_AGENT_MODULE = 'virtual:uni-devtools-agent'
const AGENT_IMPORT_MARKER = '__UNI_DEVTOOLS_AGENT_INJECTED__'

/**
 * 地址解析（方案 §4.1 约束 3）：环境变量 → 局域网 IP → localhost。
 * 微信开发者工具模拟器在本机，localhost 即可；真机/App（未来）需要 LAN IP。
 */
function resolveHost(): string {
  const fromEnv = process.env.UNI_DEVTOOLS_HOST
  if (fromEnv)
    return fromEnv
  for (const infos of Object.values(os.networkInterfaces())) {
    for (const info of infos ?? []) {
      if (info.family === 'IPv4' && !info.internal && /^(?:192\.168|10\.|172\.(?:1[6-9]|2\d|3[01]))\./.test(info.address))
        return info.address
    }
  }
  return 'localhost'
}

export interface UniDevtoolsPluginOptions {
  host?: string
  port?: number
  clientAssets?: string
}

interface PluginState {
  ready: Promise<{ panelUrl: string, wsUrl: string } | null>
  devToken: string
  started: boolean
}

/**
 * uni-app 小程序 dev 的真实运行模型是 `vite build --watch`（没有 vite dev
 * server，configureServer 不会执行），因此 devframe 采用 sidecar 模式自建
 * HTTP+WS 端口，与旧插件在 configResolved 自建 Polka 服务器的做法同构。
 */
export function UniDevtoolsPlugin(options: UniDevtoolsPluginOptions = {}): Plugin[] {
  // 生产构建（build --watch 之外的正式打包）零注入、零挂载（方案 §4.1 约束 5）
  const isDev = process.env.NODE_ENV === 'development'

  const state: PluginState = {
    ready: Promise.resolve(null),
    devToken: '',
    started: false,
  }

  function start(_config: ResolvedConfig) {
    if (state.started)
      return
    state.started = true

    const devToken = randomToken()
    state.devToken = devToken
    const registry = new AgentRegistry()
    const panelDir = resolveClientAssets(options.clientAssets)
    const def = createUniDevtoolsDevframe(registry, { clientAssets: panelDir })

    const host = options.host ?? resolveHost()
    const port = options.port ?? (process.env.UNI_DEVTOOLS_PORT ? Number(process.env.UNI_DEVTOOLS_PORT) : undefined)

    // Vite Inspect 静态托管：把 vite-plugin-inspect 的 build 产物目录（自包含
    // client UI + reports）挂到 sidecar 的 inspect 路径下供面板 iframe（官方
    // v7 Inspect tab 同款方案）。注意：经预配置 app 挂载的中间件先于 devframe
    // 自身 handler（含 auth）执行——静态报告无 token 门禁，dev 工具可接受；
    // 目录不可枚举（仅能按文件名取）
    // auth 的函数形态（(ctx) => handler）在类型上未声明，但 dev 适配器与
    // instance-shell 的 resolveAuth 运行时均支持，用 as any 绕过类型
    state.ready = createDevServer(def, {
      host,
      port,
      basePath: BASE,
      distDir: panelDir,
      app: createInspectApp(),
      mcp: false,
      openBrowser: false,
      // 小程序 connectSocket 不发 Origin 头，默认 loopback-only 检查会拒绝升级；
      // token 鉴权仍守门（FINDINGS 记录）
      allowedOrigins: false,
      auth: ((ctx: any) => createInteractiveAuth(ctx, {
        clientAuthTokens: [devToken],
        banner: () => {},
      })) as any,
      onPeerConnect: registry.connect,
      onPeerDisconnect: registry.disconnect,
    }).then((started) => {
      registry.bind(started.rpcGroup as any)
      const wsUrl = `${started.origin.replace(/^http/, 'ws')}${BASE}__ws`
      const panelUrl = `${started.origin}${BASE}?devframe_auth_token=${devToken}`
      console.log(`\n  Uni DevTools 面板 (带鉴权 token，浏览器打开):`)
      console.log(`  ${panelUrl}`)
      console.log(`  探针 WebSocket:            ${wsUrl}\n`)
      return { panelUrl, wsUrl }
    }).catch((err) => {
      console.error('[uni-devtools] devframe init failed:', err)
      return null
    })
  }

  const corePlugin: Plugin = {
    name: 'uni-devtools-devframe',

    configResolved(config) {
      if (!isDev)
        return
      start(config)
    },

    resolveId(id) {
      if (id === VIRTUAL_AGENT_MODULE)
        return `\0${VIRTUAL_AGENT_MODULE}`
      return null
    },

    async load(id) {
      if (id !== `\0${VIRTUAL_AGENT_MODULE}`)
        return null
      if (!isDev) {
        return `export const config = { wsUrl: '', token: '' }`
      }
      // 等待 sidecar 就绪，拿到真实 wsUrl（load 支持异步，不阻塞其余模块）
      const info = await state.ready
      const wsUrl = info?.wsUrl ?? ''
      return [
        `// generated by uni-devtools devframe plugin`,
        `export const config = ${JSON.stringify({
          wsUrl,
          token: wsUrl ? state.devToken : '',
          clientMarker: AGENT_CLIENT_MARKER,
        }, null, 2)}`,
      ].join('\n')
    },

    transform(code, id) {
      if (!isDev)
        return null
      if (!/\/src\/main\.[jt]s$/.test(id) || code.includes(AGENT_IMPORT_MARKER))
        return null
      return {
        code: `/* ${AGENT_IMPORT_MARKER} */\nimport { initAgent } from '@uni-helper/devtools-devframe/agent';\ninitAgent();\n${code}`,
        map: null,
      }
    },
  }

  /**
   * 编译期插桩（解决 mp 产物信息丢失，见 instrument.ts 模块头）：
   * - `__file` 注入：uni 虚拟入口（uniComponent:// / uniPage://）锚定
   *   createComponent/createPage 调用 → 探针树匿名节点改用文件名命名
   * - script setup 绑定捕获：改写「setup 返回 render 函数」的编译形态，
   *   把闭包绑定挂上 render 函数 → 探针可读可编辑 Composition API 状态
   *
   * enforce post：必须排在 uni:vue 把 SFC 编译成 mp 产物之后。
   */
  const instrumentPlugin: Plugin = {
    name: 'uni-devtools-instrument',
    enforce: 'post',
    transform(code, id) {
      if (!isDev)
        return null

      const bareId = id.split('?')[0]!

      if (bareId.startsWith('uniComponent://') || bareId.startsWith('uniPage://')) {
        const file = resolveVirtualEntryFile(bareId)
        if (!file)
          return null
        const next = injectEntryFileGuard(code, file)
        return next ? { code: next, map: null } : null
      }

      // 组件模块：script setup 闭包绑定捕获 + 渲染钩子
      if (/\.(?:vue|js|ts|jsx|tsx)$/.test(bareId)) {
        if (code.includes('setup')) {
          const next = injectSetupBindings(code, source => this.parse(source))
          if (next)
            return { code: next, map: null }
        }
        // plain <script>：render 经 _export_sfc 挂在模块层
        if (code.includes('_export_sfc')) {
          const next = injectPlainRenderHook(code)
          if (next)
            return { code: next, map: null }
        }
      }

      return null
    },
  }

  return [
    corePlugin,
    instrumentPlugin,
    // Vite Inspect：build 模式（mp dev = vite build --watch 没有 dev server，
    // 中间件模式不可用）——每个 watch rebuild 在 buildEnd 全量重写报告 +
    // 自带 client UI 到 INSPECT_OUTPUT_DIR，sidecar 静态托管给面板 iframe
    ...(isDev ? [Inspect({ build: true, outputDir: INSPECT_OUTPUT_DIR }) as Plugin] : []),
  ]
}

export const UniDevtoolsDevframe = UniDevtoolsPlugin
export default UniDevtoolsPlugin
