import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Plugin, ResolvedConfig } from 'vite'
import { createDevServer } from 'devframe/adapters/dev'
import { createInteractiveAuth } from 'devframe/recipes/interactive-auth'
import { randomToken } from 'devframe/utils/crypto-token'
import { AgentRegistry, AGENT_CLIENT_MARKER } from './relay'
import { createUniDevtoolsDevframe } from './devframe'

const BASE = '/__uni-devtools/'
const VIRTUAL_AGENT_MODULE = 'virtual:uni-devtools-agent'
const AGENT_IMPORT_MARKER = '__UNI_DEVTOOLS_AGENT_INJECTED__'

const pluginDir = path.dirname(fileURLToPath(import.meta.url))
// 面板目录兼容「源码运行（src/）」与「打包后运行（dist/plugin.mjs）」两种位置
const panelDir
  = [path.join(pluginDir, 'panel'), path.join(pluginDir, '../src/panel')]
      .find(p => fs.existsSync(p)) ?? path.join(pluginDir, './panel')

/**
 * 地址解析（方案 §4.1 约束 3）：环境变量 → 局域网 IP → localhost。
 * 微信开发者工具模拟器在本机，localhost 即可；真机/App（未来）需要 LAN IP。
 */
function resolveHost(): string {
  const fromEnv = process.env.UNI_DEVTOOLS_HOST
  if (fromEnv)
    return fromEnv
  for (const infos of Object.values(os.networkInterfaces())) {
    for (const info of infos ?? []) {
      if (info.family === 'IPv4' && !info.internal && /^(192\.168|10\.|172\.(1[6-9]|2\d|3[01]))\./.test(info.address))
        return info.address
    }
  }
  return 'localhost'
}

interface SpikeState {
  ready: Promise<{ panelUrl: string, wsUrl: string } | null>
  devToken: string
}

/**
 * uni-app 小程序 dev 的真实运行模型是 `vite build --watch`（没有 vite dev
 * server，configureServer 不会执行），因此 devframe 采用 sidecar 模式自建
 * HTTP+WS 端口，与旧插件在 configResolved 自建 Polka 服务器的做法同构。
 */
export function UniDevtoolsSpike(): Plugin {
  // 生产构建（build --watch 之外的正式打包）零注入、零挂载（方案 §4.1 约束 5）
  const isDev = process.env.NODE_ENV === 'development'

  const state: SpikeState = { ready: Promise.resolve(null), devToken: '' }

  function start(config: ResolvedConfig) {
    const devToken = randomToken()
    state.devToken = devToken
    const registry = new AgentRegistry()
    const def = createUniDevtoolsDevframe(registry)

    // auth 的函数形态（(ctx) => handler）在类型上未声明，但 dev 适配器与
    // instance-shell 的 resolveAuth 运行时均支持，spike 用 as any 绕过类型
    state.ready = createDevServer(def, {
      host: resolveHost(),
      basePath: BASE,
      distDir: panelDir,
      mcp: false,
      openBrowser: false,
      // 小程序 connectSocket 不发 Origin 头，默认 loopback-only 检查会拒绝升级；
      // token 鉴权仍守门（FINDINGS 记录）
      allowedOrigins: false,
      auth: ((ctx: any) => createInteractiveAuth(ctx, {
        clientAuthTokens: [devToken],
        banner: () => {},
      })) as any,
      onPeerConnect: registry.connect,
      onPeerDisconnect: registry.disconnect,
    }).then((started) => {
      registry.bind(started.rpcGroup as any)
      const wsUrl = `${started.origin.replace(/^http/, 'ws')}${BASE}__ws`
      const panelUrl = `${started.origin}${BASE}?devframe_auth_token=${devToken}`
      console.log(`\n  uni-devtools spike 面板(带鉴权 token，浏览器打开):`)
      console.log(`  ${panelUrl}`)
      console.log(`  探针 WebSocket:            ${wsUrl}\n`)
      return { panelUrl, wsUrl }
    }).catch((err) => {
      console.error('[uni-devtools spike] devframe init failed:', err)
      return null
    })
  }

  return {
    name: 'uni-devtools-devframe-spike',

    configResolved(config) {
      if (!isDev)
        return
      // 兼容 dev-serve（H5）：有 httpServer 时共享端口；否则 sidecar
      start(config)
    },

    resolveId(id) {
      if (id === VIRTUAL_AGENT_MODULE)
        return `\0${VIRTUAL_AGENT_MODULE}`
      return null
    },

    async load(id) {
      if (id !== `\0${VIRTUAL_AGENT_MODULE}`)
        return null
      if (!isDev) {
        return `export const config = { wsUrl: '', token: '' }`
      }
      // 等待 sidecar 就绪，拿到真实 wsUrl（load 支持异步，不阻塞其余模块）
      const info = await state.ready
      const wsUrl = info?.wsUrl ?? ''
      // 探针连接信息编译期注入：wsUrl + 预共享 token + 客户端标记
      return [
        `// generated by uni-devtools spike plugin`,
        `export const config = ${JSON.stringify({
          wsUrl,
          token: wsUrl ? state.devToken : '',
          clientMarker: AGENT_CLIENT_MARKER,
        }, null, 2)}`,
      ].join('\n')
    },

    transform(code, id) {
      if (!isDev)
        return null
      // 注入探针到应用入口（沿用 packages/plugin 的 main.ts 注入模式）
      if (!/\/src\/main\.[jt]s$/.test(id) || code.includes(AGENT_IMPORT_MARKER))
        return null
      return {
        code: `/* ${AGENT_IMPORT_MARKER} */\nimport { initAgent } from '@spike/devframe-poc/agent';\ninitAgent();\n${code}`,
        map: null,
      }
    },
  }
}
