/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppLogos: typeof import('./components/AppLogos.vue')['default']
    CompositionScript: typeof import('./components/CompositionScript.vue')['default']
    DemosAttrsFallthroughDemo: typeof import('./components/demos/AttrsFallthroughDemo.vue')['default']
    DemosDynamicKeepAliveDemo: typeof import('./components/demos/DynamicKeepAliveDemo.vue')['default']
    DemosEventsEmitsDemo: typeof import('./components/demos/EventsEmitsDemo.vue')['default']
    DemosExposeRefsDemo: typeof import('./components/demos/ExposeRefsDemo.vue')['default']
    DemosKeepAliveTabA: typeof import('./components/demos/KeepAliveTabA.vue')['default']
    DemosKeepAliveTabB: typeof import('./components/demos/KeepAliveTabB.vue')['default']
    DemosKeepAliveTabC: typeof import('./components/demos/KeepAliveTabC.vue')['default']
    DemosModelTwoWayDemo: typeof import('./components/demos/ModelTwoWayDemo.vue')['default']
    DemosOptionsApiFullDemo: typeof import('./components/demos/OptionsApiFullDemo.vue')['default']
    DemosPropsAdvancedDemo: typeof import('./components/demos/PropsAdvancedDemo.vue')['default']
    DemosPropsBasicDemo: typeof import('./components/demos/PropsBasicDemo.vue')['default']
    DemosProvideInjectChild: typeof import('./components/demos/ProvideInjectChild.vue')['default']
    DemosProvideInjectGrandchild: typeof import('./components/demos/ProvideInjectGrandchild.vue')['default']
    DemosProvideInjectOptionsChild: typeof import('./components/demos/ProvideInjectOptionsChild.vue')['default']
    DemosProvideInjectParent: typeof import('./components/demos/ProvideInjectParent.vue')['default']
    DemosReactivityFullDemo: typeof import('./components/demos/ReactivityFullDemo.vue')['default']
    DemosSlotsScopedDemo: typeof import('./components/demos/SlotsScopedDemo.vue')['default']
    DemosTreeDemo: typeof import('./components/demos/TreeDemo.vue')['default']
    DemosTreeNode: typeof import('./components/demos/TreeNode.vue')['default']
    HiCounter: typeof import('./components/HiCounter.vue')['default']
    InputEntry: typeof import('./components/InputEntry.vue')['default']
    OptionsScript: typeof import('./components/OptionsScript.vue')['default']
    TestComp: typeof import('./components/TestComp.vue')['default']
  }
}
